### ISSUE TITLE
self._on_connect call is missing 'initial_data' parameter

### ISSUE THREAD

**Issue by kauhmi81** [xmikos/hangupsbot#10]
Hangupsbot does not connect and gives error: "_on_connect() missing required positional argument 'initial_data'".

On line 179 the call is missing the 'initial_data' variable:
self._clienton_connect.add_observer(self._on_connect)

Best regards:
Mikael

**Comment by wardellbagby** [comment]
@kauhmi81 I've already created a potential fix for this. See my pull request, #9, and feel free to use that branch until @xmikos either accepts it or updates the main verse.

**Comment by xmikos** [comment]
This is fixed in HangupsBot >= 1.7.0. Btw. thanks to @wardellchandler for additional fixes (merged in 1.7.1).
