### ISSUE TITLE
how do i integrate hangupsbot with a bot made in "api.ai"?

### ISSUE THREAD

**Issue by Gauravtolani** [xmikos/hangupsbot#18]
I have made a bot in **api.ai**, but they don't provide integration with **hangouts**. hangupsbot seems to be the solution but I am not sure, is it possible?.
If its possible, how do I use hangups bot as a webservice to get and respond to the bot made in **api.ai**.

**Comment by yashchoubey** [comment]
Done by using http requests. Thanks for making a robust project @xmikos , it was very easy to implement using hangupsbot.

**Comment by Gauravtolani** [comment]
done by using http requests. thanks for making a robust project @xmikos .
