### ISSUE TITLE
Question about conv_leave

### ISSUE THREAD

**Issue by Deuteu** [xmikos/hangupsbot#4]
At https://github.com/xmikos/hangupsbot/blob/5a283cf38640754feec30f0d3e4ab69e78d7f54d/hangupsbot/commands/conversations.py#L105

It is said that the usage is "/bot leave" whereas all other command, the in-chat-command is the same name as the python function. I don't see any redefinition for this particular case. Is that a mistake in code or am I missing something?

Thanks.

PS : Are issues a good way to ask this kind of question? Or is there a better way?

**Comment by xmikos** [comment]
It was only mistake in docstring (should be now fixed).
