### ISSUE TITLE
Getting Started Guide?

### ISSUE THREAD

**Issue by queuebit** [xmikos/hangupsbot#6]
I just got hangups and hangupsbot setup and running.

I am not quite sure how to configure hangupsbot to do autoreplies and handle commands.

``` json
{
  "admins": ["MY_USERNAME"],
  "autoreplies": [
    [["hi", "hello"], "Hello world!"],
    [["bot"], "At your service!"]
  ],
  "autoreplies_enabled": true,
  "commands_admin": ["quit", "config"],
  "commands_enabled": true,
  "commands_aliases": ["/bot", "/hal", "/cylon", "/skynet", "/terminator"],
  "forwarding_enabled": true,
  "conversations": {
    "UgwELlTjFXV9qwSBsB94AaABAQ": {
      "autoreplies_enabled": true,
      "commands_enabled": true
    }
  }
}
```

I have one conversation that I want to be active, but when I message in that chat, nothing seems to be happening.

**Comment by xmikos** [comment]
With this default config, if you invite bot's Hangouts account to a conversation, it should start responding immediately (to `/bot` commands, autoreplies, etc.). If it doesn't work, chances are that bot's Hangouts account doesn't have invitations allowed from anyone.

So if you invite bot to conversation, Google doesn't add that account to conversation automatically, you must log in to GMail with bot's account and manually accept that invitatation. Or you can set invitation policy to accept invitations from anyone (default is to accept only invitations from people in your G+ Circles).

I will add this to documentation with another update...

**Comment by queuebit** [comment]
That ended up working for me. I redid the auth with another Google account I had, started a 1:1 conversation with that account, signed into GMail to accept the Hangout invitation and poof it is working now.

I am still having some issues getting the "I'm sorry, Dave" message, but I will look into the code and see what is going on.

Thanks!
