### ISSUE TITLE
Inevitable crash

### ISSUE THREAD

**Issue by altercation** [xmikos/hangupsbot#7]
I seem to be experiencing an inevitable crash of hangupsbot. Not sure if you are still working on it, so no worries if not, but fwiw, the relevant traceback is below.

This has occurred each time I've tested it, a couple minutes into running and successful bot responses.

```
Exception ignored in: <bound method _UnixSelectorEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/base_events.py", line 361, in __del__
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 57, in close
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 138, in remove_signal_handler
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by altercation** [comment]
Well... I'm seeing this on hangups as well, so I'd go ahead and close this issue if you think it's probably an error there, not in hangupsbot. Sorry to trouble :)

**Comment by Gauravtolani** [comment]
@altercation how did you solve the problem? I am getting the same error too and there seems to be no issue like this mentioned in hangups issues list.
